name: vncitizens_home
description: vnCitizens Home Package
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  assets:
    - packages/vncitizens_home/assets/header.png
    # menu
    - packages/vncitizens_home/assets/menu/asxh.png
    - packages/vncitizens_home/assets/menu/camera.png
    - packages/vncitizens_home/assets/menu/ca_nhan.png
    - packages/vncitizens_home/assets/menu/chinh_quyen.png
    - packages/vncitizens_home/assets/menu/dat_dai.png
    - packages/vncitizens_home/assets/menu/dvc.png
    - packages/vncitizens_home/assets/menu/giao_duc.png
    - packages/vncitizens_home/assets/menu/giao_thong.png
    - packages/vncitizens_home/assets/menu/nong_nghiep.png
    - packages/vncitizens_home/assets/menu/pcd_covid19.png
    - packages/vncitizens_home/assets/menu/phan_anh.png
    - packages/vncitizens_home/assets/menu/thanh_toan.png
    - packages/vncitizens_home/assets/menu/thong_tin_can_biet.png
    - packages/vncitizens_home/assets/menu/tin_tuc.png
    - packages/vncitizens_home/assets/menu/y_te.png
    - packages/vncitizens_home/assets/menu/thong_tin_can_biet.png
    # bottom navigation
    - packages/vncitizens_home/assets/bottom_nav/cai_dat.png
    - packages/vncitizens_home/assets/bottom_nav/menu.png
    - packages/vncitizens_home/assets/bottom_nav/thong_bao.png
    - packages/vncitizens_home/assets/bottom_nav/trang_chu.png

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
